# Generated by Django 3.0.4 on 2020-04-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='fulfield',
            new_name='fulfilled',
        ),
    ]
